[naviroom]
# Replace with your Linux server info
# Example:
# prod ansible_host=203.0.113.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
prod ansible_host=118.89.91.106 ansible_user=ubuntu ansible_connection=ssh
