---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - git
      - rsync
      - curl
      - python3
      - python3-pip
      - python3-venv
      - python3-pymysql
    state: present
    update_cache: true
    lock_timeout: 600

- name: Ensure pip tools are present
  ansible.builtin.pip:
    name:
      - setuptools
      - wheel
    executable: pip3
